### PR TITLE
Update Contact.js

### PR DESCRIPTION
**Pull request by rankworks**

### CODE REVIEW

**Comment by rankworks** [comment]
merge

**Review by rankworks — COMMENTED** [review]
change

**Comment by rankworks** [comment]
change

**Review by RockRuth — APPROVED** [review]
dd

**Review by kbooth1000 — COMMENTED** [review]
The phone # was updated in a separate commit.

**Comment by RockRuth** [comment]
Sounds good thanks. On Tue, Nov 10, 2020 at 12:30 PM Kyle Booth <notifications@github.com> wrote:
@kbooth1000 commented on this pull request.

The phone # was updated in a separate commit.

?You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Dustin McCainPresident RockRuth Heating & Airwww.RockRuth.com(305) 433-1065(770) 693-2946

**Pull request closed without merging**
